### ISSUE TITLE
handle downtime of Algolia 

### ISSUE THREAD

**Issue by did** [Papipo/activesearch#2]
HTTParty throws a "Errno::ECONNRESET: Connection reset by peer" error when it reaches Algolia to perform a save (activesearch-0.0.15/lib/activesearch/algolia/client.rb:28). 
Is it the responsibility of the main app to handle the error or the gem itself ?

**Comment by Papipo** [comment]
I guess that the gem can hide this issue from the main app.

In the end, using a messaging queue would be the best way to index documents instead of relying on after_save callbacks, and it would just retry if algolia is down at some point.

In case that you don't want to use a queue, there is the rake task to reindex a model too.
